SELECT * 
FROM customer

--Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, sum(purchase_amount) as total_revenue_by_gender  
FROM customer
GROUP BY gender 

--Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id ,purchase_amount
FROM customer 
WHERE discount_applied ='Yes' and purchase_amount> (SELECT avg(purchase_amount)
FROM customer ) 

> --Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(avg(review_rating::numeric),2) as avg_review_rating 
FROM customer
GROUP BY item_purchased
order by avg(review_rating) desc 
limit 5

› --Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT shipping_type, ROUND(avg(purchase_amount)::numeric,2) as avg_amount
FROM customer
WHERE shipping_type in ('Express','Standard')
GROUP BY shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between
› --subscribers and non-subscribers.

SELECT subscription_status, 
count(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer 
GROUP BY subscription_status 
order by total_revenue, avg_spend desc ; 

› --Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
ROUND(100* SUM(CASE WHEN discount_applied='Yes' THEN 1 else 0 END)/count(*),2) as discount_rate 
FROM customer 
GROUP BY item_purchased
ORDER BY discount_rate  desc
LIMIT 5 


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
SELECT customer_id , previous_purchases,
CASE 
	WHEN previous_purchases =1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment 
from customer
)

SELECT customer_segment, count(*) as "Number of Customers"
FROM customer_type
GROUP BY customer_segment 



--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
	SELECT category, 
	item_purchased,
	count(*) as total_orders,
	ROW_NUMBER() over(partition by category order by count(*) desc ) as item_rank 
FROM customer 
GROUP BY category, item_purchased )

SELECT category,item_purchased, total_orders, item_rank 
FROM item_counts 
WHERE item_rank<=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, count(customer_id) as repeat_buyers
FROM customer 
WHERE previous_purchases>5
GROUP BY subscription_status


--Q10. What is the revenue contribution of each age group? I
SELECT age_group, sum(purchase_amount) as total_revenue  
FROM customer
GROUP BY age_group 
ORDER BY total_revenue desc

